<div id="head_wrap">	
	<!--  START LOGO -->
    <div id="logo">
        <h1>
            <a href="<?php echo Conexion::ruta();?>" title="Intranet">
            	<img class="fade" alt="Sistemas" src="<?php echo Conexion::ruta();?>public/images/LogoSB.png" border="0" />
            </a>
        </h1>
    </div>
    
    <!--  END LOGO  -->
	
	<!--  START LOGIN -->
    <div id="login">
        <!-- MODAL LINK - POINT THIS LINK TO YOUR EXTERNAL HTML FILE AND AMEND THE HEIGHT/WIDTH ACCORDINGLY -->
        
        <span id="spanreloj" class="highlight"></span>
        &nbsp;&nbsp;||&nbsp;&nbsp;
        <span class="highlight"><?php echo Conexion::fecha();?></span>
        
	</div>
    
    
</div><!--  end div #head_wrap -->