<!DOCTYPE html >
<html lang= "es" >
<head>
	<title>..:: Intranet  - Abrir-Cerrar Mes ::..</title>
    <meta charset = "utf-8" />
    <meta name="description" content="Bienvenido a mi sitio" />
    <meta name = "viewport" content ="width= devide-with, inicial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href= "<?php echo Conexion::ruta();?>public/images/favicon.ico" />
    <link rel="author" type="text/plain" href= "humans.txt" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href= "sitemap.xml" />
 	
    <link href="<?php echo Conexion::ruta();?>public/css/smoothness/jquery-ui-1.8.23.custom.css" rel="stylesheet" media="screen">

    <!--
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/datatables.css" />
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/TableTools.css" />
    -->

    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/jquery.dataTables.min.css" />

	
    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/estilos.css" />
    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/menu.css" />


    
  
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/jquery/jquery.1.8.1.js"></script>
	<script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/jquery_ui/jquery-ui-1.8.23.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/datatables.js"></script>
    
    <!--<script type="text/javascript" src="<?php //echo Conectar::ruta();?>public/js/TableTools.js"></script> -->
    
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/pdfmake.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/jszip.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/vfs_fonts.js"></script>


    
	<script language="javascript" type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/funciones.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/funcionesPer.js"></script>
   
   
</head>

<body onload="muestraReloj(); document.form.reset();document.form.id.focus();">
    <header>
        <!--  START HEADER -->
        <div id="header">
            <!--  START HEAD_WRAP -->
            <?php include("header.phtml");?>
            <!--  END HEAD_WRAP -->
        </div><!--  end div #header -->
        <!--  END HEADER -->   
    </header>
    
    <section id="contenido">
        <section id="principal">
            <article id="Info">
                <!--  START CONTENT WRAPPER -->
                <div id="content_wrapper">
                    <!--  START PRIMARY CONTENT -->
                    <div id="primary_content">
						<h3>Abrir o cerrar meses en linea</h3>
						<div id="MenuDatos">
                            <table>
                                <tr>
                                    
                                </tr>
                            </table>
                        </div>	
						<form action="" method="post" name="form" enctype="multipart/form-data">
							<fieldset>
                            	<legend>Abrir Cerrar Mes</legend>
                                <table>
                                    <tr>
                                        <td valign="top" align="left" colspan="5">
                                            <select name="ano" id="ano">
                                                <option value="0">Seleccione año</option>
                                                <option value="2020">2020</option>
                                                <option value="2021">2021</option>
                                                
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        
                                    </tr>
                                    <tr>
                                        <td valign="middle" align="left" >
                                            <div id="btnEned"><a href="javascript:void(0);" data-accion="guardar" title="Enero" ><img id="btnEne" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnFebd"><a href="javascript:void(0);" data-accion="guardar" title="Febrero" ><img id="btnFeb" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnMard"><a href="javascript:void(0);" data-accion="guardar" title="Marzo" ><img id="btnMar" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnAbrd"><a href="javascript:void(0);" data-accion="guardar" title="Abril" ><img id="btnAbr" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnMayd"><a href="javascript:void(0);" data-accion="guardar" title="Mayo" ><img id="btnMay" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnJund"><a href="javascript:void(0);" data-accion="guardar" title="Junio" ><img id="btnJun" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnJUld"><a href="javascript:void(0);" data-accion="guardar" title="Julio" ><img id="btnJul" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnAgod"><a href="javascript:void(0);" data-accion="guardar" title="Agosto" ><img id="btnAgo" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnSepd"><a href="javascript:void(0);" data-accion="guardar" title="Septiembre" ><img id="btnSep" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnOctd"><a href="javascript:void(0);" data-accion="guardar" title="Octubre" ><img id="btnOct" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnNovd"><a href="javascript:void(0);" data-accion="guardar" title="Noviembre" ><img id="btnNov" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                        <td valign="middle" align="left" >
                                            <div id="btnDicd"><a href="javascript:void(0);" data-accion="guardar" title="Diciembre" ><img id="btnDic" src="" border="0" width="34" height="34" /></a></div>
                                        </td>
                                    </tr>
                                </table>
                            </fieldset>
						</form>
                        <div id="dialogo-borrarArt" title="Eliminar Registro" style="display:none;">
                            <p>El registro se eliminará permanentemente de la Base de Datos. ¿Desea continuar?</p>
                        </div>
                        <div id="dialogo-maestroArt" title="Maestro de Registros" style="display:none;">
                            <table id="tableArt" class="display" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>UM</th>
                                    </tr>
                                </thead>

                                <tbody id="listaarticulos">
                                    
                                </tbody>
                                
                                <tfoot>
                                </tfoot>
                                
                            </table>  
                        </div>
             			
					</div>
					<!--  END PRIMARY CONTENT -->   
                </div><!--  end div #content_wrapper -->
                <!--  END CONTENT_WRAPPER -->
        	</article>
        </section>
        
        <aside>
        	<!--  START SIDEBAR -->
            <?php include("sidebar.phtml");?>
            <!--  end div #sidebar -->
            <!--  END SIDEBAR -->
        
        </aside>
        
        
    </section>
    
    <footer>
        <!--  START FOOTER -->
        <div id="footer">
            <p>
            <?php include("footer.phtml");?>
            </p>
        </div>
        <!--  END CEND -->
    </footer>
</body>
</html>

