<!DOCTYPE html >
<html lang= "es" >
<head>
	<title>..:: Intranet  - Registros del kardex ::..</title>
    <meta charset = "utf-8" />
    <meta name="description" content="Bienvenido a mi sitio" />
    <meta name = "viewport" content ="width= devide-with, inicial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href= "<?php echo Conectar::ruta();?>public/images/favicon.ico" />
    <link rel="author" type="text/plain" href= "humans.txt" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href= "sitemap.xml" />
 	
    <link href="<?php echo Conectar::ruta();?>public/css/smoothness/jquery-ui-1.8.23.custom.css" rel="stylesheet" media="screen">

    <!--
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/datatables.css" />
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/TableTools.css" />
    -->

    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/jquery.dataTables.min.css" />

	
    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/estilos.css" />
    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/menu.css" />


    
  
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery/jquery.1.8.1.js"></script>
	<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery_ui/jquery-ui-1.8.23.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/datatables.js"></script>
    
    <!--<script type="text/javascript" src="<?php //echo Conectar::ruta();?>public/js/TableTools.js"></script> -->
    
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/pdfmake.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jszip.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/vfs_fonts.js"></script>


    
	<script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/funciones.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/funcionesRegKar.js"></script>
   
   
</head>

<body onload="muestraReloj(); document.form.reset();document.form.id.focus();">
    <header>
        <!--  START HEADER -->
        <div id="header">
            <!--  START HEAD_WRAP -->
            <?php include("header.phtml");?>
            <!--  END HEAD_WRAP -->
        </div><!--  end div #header -->
        <!--  END HEADER -->   
    </header>
    
    <section id="contenido">
        <section id="principal">
            <article id="Info">
                <!--  START CONTENT WRAPPER -->
                <div id="content_wrapper">
                    <!--  START PRIMARY CONTENT -->
                    <div id="primary_content">
						<h3>Registros del kardex</h3>
						<div id="MenuDatos">
                            <form>
                                <table>
                                    <tr>
                                        <td valign="top" align="left" >
                                            <label for="id">Desde:</label>
                                        </td>
                                        <td valign="top" align="left" width="10">
                                            <input name="desdefecha" type="date" class="fade" id="desdefecha" />
                                        </td>                                   
                                        <td valign="top" align="left" width="50">
                                            <input name="desdeidart" type="text" class="fade" id="desdeidart" value="" dir="rtl" onkeypress="return soloNumeros(event);" required />
                                        </td>
                                        <td align="center">
                                            <div id="btnMaestroArtDesde"><a href="javascript:void(0);" data-accion="" title="Buscar Registro" ><img src="<?php echo Conectar::ruta();?>public/images/search_button_32.png" border="0" width="24" height="24" /></a></div>
                                         </td>
                                         <td valign="top" align="left">
                                            <select id="tipo" class="fade" name="tipo">
                                                <option value="0">Seleccione tipo movimiento</option>
                                                <?php
                                                  $form="tipocompr";
                                                  include("controller/formularioController.php");
                                                  for($i=0;$i<sizeof($datos);$i++)
                                                  {
                                                ?>
                                                <option value="<?php echo $datos[$i]["idtipomov"];?>" title="<?php echo $datos[$i]["descripcion"];?>"><?php echo $datos[$i]["descripcion"];?></option>
                               
                                                <?php
                                                  }
                                                ?>
                                            </select>
                                        </td>
                                        <td valign="top" align="left">
                                            <input type="button" value="Generar" title="Generar" name="btnGenerar" id="btnGenerar" onclick="" />          
                                        </td>
                                    </tr>

                                    <tr>
                                        <td valign="top" align="left" >
                                            <label for="idart">Hasta:</label>
                                        </td>
                                        <td valign="top" align="left" width="10">
                                            <input name="hastafecha" type="date" class="fade" id="hastafecha" value="" required />
                                        </td>
                                        <td valign="top" align="left" width="50">
                                            <input name="hastaidart" type="text" class="fade" id="hastaidart" value="" dir="rtl" onkeypress="return soloNumeros(event);" required />
                                        </td>
                                        <td align="center">
                                            <div id="btnMaestroArtHasta"><a href="javascript:void(0);" data-accion="" title="Buscar Registro" ><img src="<?php echo Conectar::ruta();?>public/images/search_button_32.png" border="0" width="24" height="24" /></a></div>
                                         </td>
                                    </tr>       
                                </table>
                            </form>
                        </div>	
						
                    	<div id="TablaDatos">
                            <table id="tablaReg" class="display" cellspacing="0" width="95%">
                                <thead>
                                    <tr>
                                        <th>Folio</th>
                                        <th>Tipo</th>
                                        <th>Fecha</th>
                                        <th>Comentario</th>
                                        <th>Id</th>
                                        <th>Codigo</th>
                                        <th>Articulo</th>
                                        <th>Entrada</th>
                                        <th>Salida</th>
                                        <th>Centro</th>
                                        <th>Cuenta</th>
                                    </tr>
                                </thead>
                                 
                                <tbody id="listaregistros">  
                                </tbody>
                                
                                <tfoot>
                                </tfoot>
                                
                            </table>  
                        </div>
	
					</div>
					<!--  END PRIMARY CONTENT -->   
                </div><!--  end div #content_wrapper -->
                <!--  END CONTENT_WRAPPER -->
        	</article>
        </section>
        
        <aside>
        	<!--  START SIDEBAR -->
            <?php include("sidebar.phtml");?>
            <!--  end div #sidebar -->
            <!--  END SIDEBAR -->
        
        </aside>
        
        
    </section>
    
    <footer>
        <!--  START FOOTER -->
        <div id="footer">
            <p>
            <?php include("footer.phtml");?>
            </p>
        </div>
        <!--  END CEND -->
    </footer>
</body>
</html>

