<!DOCTYPE html >
<html lang= "es" >
<head>
	<title>..:: Tesoreria ::..</title>
    <meta charset = "utf-8" />
    <meta name="description" content="Bienvenido a mi sitio" />
    <meta name = "viewport" content ="width= devide-with, inicial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href= "<?php echo Conexion::ruta();?>public/images/favicon.ico" />
    <link rel="author" type="text/plain" href= "humans.txt" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href= "sitemap.xml" />
 	
    <link href="<?php echo Conexion::ruta();?>public/css/smoothness/jquery-ui-1.8.23.custom.css" rel="stylesheet" media="screen">

    <!--
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/datatables.css" />
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/TableTools.css" />
    -->

    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/jquery.dataTables.min.css" />

	
    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/estilos.css" />
    <link rel="stylesheet" href= "<?php echo Conexion::ruta();?>public/css/menu.css" />


    
  
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/jquery/jquery.1.8.1.js"></script>
	<script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/jquery_ui/jquery-ui-1.8.23.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/datatables.js"></script>
    
    <!--<script type="text/javascript" src="<?php //echo Conectar::ruta();?>public/js/TableTools.js"></script> -->
    
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/pdfmake.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/jszip.min.js"></script>
    <script type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/vfs_fonts.js"></script>


    
	<script language="javascript" type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/funciones.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo Conexion::ruta();?>public/js/funcionesTeso.js"></script>
   
   
</head>

<body onload="muestraReloj(); document.form.reset();document.form.id.focus();">
    <header>
        <!--  START HEADER -->
        <div id="header">
            <!--  START HEAD_WRAP -->
            <?php include("header.phtml");?>
            <!--  END HEAD_WRAP -->
        </div><!--  end div #header -->
        <!--  END HEADER -->   
    </header>
    
    <section id="contenido">
        <section id="principal">
            <article id="Info">
                <!--  START CONTENT WRAPPER -->
                <div id="content_wrapper">
                    <!--  START PRIMARY CONTENT -->
                    <div id="primary_content">
						<h3>Control pago de Rendiciones</h3>
						<div id="MenuDatos">
                            <form>
                                <table>
                                    <tr>
                                        <td valign="top" align="left" >
                                            <label for="id">Desde:</label>
                                        </td>

                                        <td valign="top" align="left" width="10">
                                            <input name="desdefecha" type="date" class="fade" id="desdefecha" />
                                        </td>

                                        <td valign="top" align="left" >
                                            <label for="idart">Hasta:</label>
                                        </td>

                                        <td valign="top" align="left" width="10">
                                            <input name="hastafecha" type="date" class="fade" id="hastafecha" value="" required />
                                        </td>                                   
                                             
                                        <td valign="top" align="left">
                                            <input type="button" value="Generar" title="Generar" name="btnGenerar" id="btnGenerar" onclick="" />          
                                        </td>
                                    </tr>
                                </table>

                                <table>
                                    <tr>
                                        <td valign="top" align="left" width="25">
                                            <input name="codrend" type="text" class="fade" id="codrend" value="" onblur="" dir="rtl" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="20">
                                            <input name="folio" type="text" class="fade" id="folio" value="" onblur="" dir="rtl" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="87">
                                            <input name="fecha" type="text" class="fade" id="fecha" value="" onblur="" dir="rtl" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="180">
                                            <input name="usuario" type="text" class="fade" id="usuario" value="" onblur="" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="60">
                                            <input name="empresa" type="text" class="fade" id="empresa" value="" onblur="" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="60">
                                            <input name="estado" type="text" class="fade" id="estado" value="" onblur="" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left">
                                            <input name="monto" type="text" class="fade" id="monto" value="" onblur="" dir="rtl" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="75">
                                            <input name="aprobar" type="text" class="fade" id="aprobar" value="" onblur="" readonly="readonly" required/>
                                        </td>

                                        <td valign="top" align="left" width="70">
                                            <input name="contab" type="text" class="fade" id="contab" value="" onblur="" readonly="readonly" required/>
                                        </td>

                                        <td valign="center" align="left" width="70">
                                            <input name="pago" type="checkbox" id="pago"/> Pagar
                                        </td>                               
                                             
                                        <td valign="middle" align="left" width="30">
                                            <div id="btnGuardarRend"><a href="javascript:void(0);" data-accion="guardarrend" title="Guardar Registro" ><img src="<?php echo Conexion::ruta();?>public/images/save_as.png" border="0" width="24" height="24" /></a></div>
                                        </td>      
                                    </tr>
                                </table>

                            </form>
                        </div>	
						
                    	<div id="TablaDatos">
                            <table id="tablaReg" class="display" cellspacing="0" width="95%">
                                <thead>
                                    <tr>
                                        <th>Codrend</th>
                                        <th>Folio</th>
                                        <th>Fecha</th>
                                        <th>Usuario</th>
                                        <th>Empresa</th>
                                        <th>Estado</th>
                                        <th>Monto</th>
                                        <th>Detalle</th>
                                        <th>Aprobar</th>
                                        <th>Contab</th>
                                        <th>Pago</th>
                                    </tr>
                                </thead>
                                 
                                <tbody id="listaregistros">  
                                </tbody>
                                
                                <tfoot>
                                </tfoot>
                                
                            </table>  
                        </div>
                            
                        
             			
					</div>
					<!--  END PRIMARY CONTENT -->   
                </div><!--  end div #content_wrapper -->
                <!--  END CONTENT_WRAPPER -->
        	</article>
        </section>
        
        <aside>
        	<!--  START SIDEBAR -->
            <?php include("sidebar.phtml");?>
            <!--  end div #sidebar -->
            <!--  END SIDEBAR -->
        
        </aside>
        
        
    </section>
    
    <footer>
        <!--  START FOOTER -->
        <div id="footer">
            <p>
            <?php include("footer.phtml");?>
            </p>
        </div>
        <!--  END CEND -->
    </footer>
</body>
</html>

