<!DOCTYPE html >
<html lang= "es" >
<head>
	<title>..:: Usuarios ::..</title>
    <meta charset = "utf-8" />
    <meta name="description" content="Bienvenido a mi sitio" />
    <meta name = "viewport" content ="width= devide-with, inicial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href= "<?php echo Conectar::ruta();?>public/images/favicon.ico" />
    <link rel="author" type="text/plain" href= "humans.txt" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href= "sitemap.xml" />
 	
    <link href="<?php echo Conectar::ruta();?>public/css/smoothness/jquery-ui-1.8.23.custom.css" rel="stylesheet" media="screen">

    <!--
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/datatables.css" />
    <link rel="stylesheet" href= "<?php //echo Conectar::ruta();?>public/css/TableTools.css" />
    -->

    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/jquery.dataTables.min.css" />

	
    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/estilos.css" />
    <link rel="stylesheet" href= "<?php echo Conectar::ruta();?>public/css/menu.css" />


    
  
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery/jquery.1.8.1.js"></script>
	<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery_ui/jquery-ui-1.8.23.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/datatables.js"></script>
    
    <!--<script type="text/javascript" src="<?php //echo Conectar::ruta();?>public/js/TableTools.js"></script> -->
    
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/pdfmake.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jszip.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/vfs_fonts.js"></script>


    
	<script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/funciones.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/funcionesUsu.js"></script>
   
   
</head>

<body onload="muestraReloj(); document.form.reset();document.form.id.focus();">
    <header>
        <!--  START HEADER -->
        <div id="header">
            <!--  START HEAD_WRAP -->
            <?php include("header.phtml");?>
            <!--  END HEAD_WRAP -->
        </div><!--  end div #header -->
        <!--  END HEADER -->   
    </header>
    
    <section id="contenido">
        <section id="principal">
            <article id="Info">
                <!--  START CONTENT WRAPPER -->
                <div id="content_wrapper">
                    <!--  START PRIMARY CONTENT -->
                    <div id="primary_content">
						<h3>Maestro Usuarios</h3>
						<div id="MenuDatos">
                            <table>
                                <tr>
                                    <td valign="middle" align="left">
                                    <div id="btnPrimerUsu"><a href="javascript:void(0);" data-accion="ultimo" title="Primer Registro"><img src="<?php echo Conectar::ruta();?>public/images/resultset_first.png" border="0" width="24" height="24" /></a></div>
                                    </td>
                                    
                                    <td valign="middle" align="left">
                                    <div id="btnAnteriorUsu"><a href="javascript:void(0);" data-accion="anterior" title="Anterior"><img src="<?php echo Conectar::ruta();?>public/images/resultset_previous.png" border="0" width="24" height="24" /></a></div>
                                    </td>
                                    
                                    <td valign="middle" align="left">
                                    <div id="btnSiguienteUsu"><a href="javascript:void(0);" data-accion="siguiente" title="Siguiente"><img src="<?php echo Conectar::ruta();?>public/images/resultset_next.png" border="0" width="24" height="24" /></a></div>
                                    </td>
                                    
                                    <td valign="middle" align="left">
                                    <div id="btnUltimoUsu"><a href="javascript:void(0);" data-accion="ultimo" title="Ultimo Registro" ><img src="<?php echo Conectar::ruta();?>public/images/resultset_last.png" border="0" width="24" height="24" /></a></div>
                                    </td>
                                    
                                    <td valign="middle" align="left" width="30">
                                    <a href="" title=""></a>
                                    </td>
                                    
                                    <td valign="middle" align="left">
                                    <a href="<?php echo Conectar::ruta();?>usuarios/"  title="Nuevo Registro"><img src="<?php echo Conectar::ruta();?>public/images/server_add.png" border="0" width="24" height="24" /></a>
                                    </td>
                                    
                                    <td valign="middle" align="left" >
                                    <div id="btnGuardarUsu"><a href="javascript:void(0);" data-accion="guardar" title="Guardar Registro" ><img src="<?php echo Conectar::ruta();?>public/images/save_as.png" border="0" width="24" height="24" /></a></div>
                                    </td>
                                    
                                    <td valign="middle" align="left">
                                    <div id="btnBorrarUsu"><a href="javascript:void(0);" data-accion="eliminar" title="Eliminar Registo" ><img src="<?php echo Conectar::ruta();?>public/images/bin_empty.png" border="0" width="24" height="24" /></a></div>
                                    </td>
                                    
                                    <td valign="middle" align="left" width="20">
                                    <a href="" title=""></a>
                                    </td>
                                    
                                    <td valign="middle" align="left" >
                                   <div id="btnImprimirUsu"><a href="javascript:void(0);" onclick="" title="Imprimir" ><img src="<?php echo Conectar::ruta();?>public/images/printer.png" border="0" width="24" height="24" /></a></div>
                                   </td>
                                </tr>
                            </table>
                        </div>	
						<form action="" method="post" name="form" enctype="multipart/form-data">
							<fieldset>
                            	<legend>Datos</legend>
                                <table>
                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="id">Codigo Usuario:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <input name="id" type="text" class="fade" id="id" value="" onkeypress="return soloNumeros(event);" onblur="buscar()" required/>
                                         </td>
                                         <td align="center">
                                             <div id="btnMaestroUsu"><a href="javascript:void(0);" data-accion="" title="Buscar Registro" ><img src="<?php echo Conectar::ruta();?>public/images/search_button_32.png" border="0" width="24" height="24" /></a></div>
                                             <!-- 
                                             <a href="" title="Buscar Registro" onclick="popupArt()"><img src="<?php //echo Conectar::ruta();?>public/images/search_button_32.png" border="0" width="24" height="24"></a>
                                             -->
                                         </td>
                                        
                                    </tr>
                                        
                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="log">Login:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <input name="log" type="text" class="fade" id="log" value="" required />
                                        </td>
                                    </tr>
                                    
                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="nombre">Nombre:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <input name="nombre" type="text" class="fade" id="nombre" value="" required />
                                        </td>
                                    </tr>
                                    
                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="correo">Correo:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <input name="correo" type="text" class="fade" id="correo" value=""  required/>
                                        </td>
                                    </tr>
                                    
                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="password">Password:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <input name="password" type="text" class="fade" id="password" value=""  required/>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="firma">Firma:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <input name="firma" type="text" class="fade" id="firma" value=""  required/>
                                        </td>
                                    </tr>
                                                   
                                    <tr>
                                        <td valign="top" align="left">
                                            <label for="admin">Tipo:</label>
                                        </td>
                                        <td valign="top" align="left">
                                            <select id="admin" class="fade" name="admin" >
                                                <option value="0">Tipo Usuario</option>
                                                <option value="1">Administrador</option>
                                                <option value="2">Normal</option>
                                            </select>
                                        </td>
                                    </tr>

                                    <tr>
                                    	<td valign="top" align="left">
                                            <input type="hidden" id="reg" name="reg" value="0" />
                                        </td>
                                    </tr>
                                    
                                </table>
                            </fieldset>
						</form>
                        <div id="dialogo-borrarUsu" title="Eliminar Registro" style="display:none;">
                            <p>El registro se eliminará permanentemente de la Base de Datos. ¿Desea continuar?</p>
                        </div>
                        <div id="dialogo-maestroUsu" title="Maestro de Registros" style="display:none;">
                            <table id="tableUsu" class="display" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Codigo</th>
                                        <th>Log</th>
                                        <th>Nombre</th>
                                    </tr>
                                </thead>

                                <tbody id="listausuarios">
                                    
                                </tbody>
                                
                                <tfoot>
                                </tfoot>
                                
                            </table>  
                        </div>
             			
					</div>
					<!--  END PRIMARY CONTENT -->   
                </div><!--  end div #content_wrapper -->
                <!--  END CONTENT_WRAPPER -->
        	</article>
        </section>
        
        <aside>
        	<!--  START SIDEBAR -->
            <?php include("sidebar.phtml");?>
            <!--  end div #sidebar -->
            <!--  END SIDEBAR -->
        
        </aside>
        
        
    </section>
    
    <footer>
        <!--  START FOOTER -->
        <div id="footer">
            <p>
            <?php include("footer.phtml");?>
            </p>
        </div>
        <!--  END CEND -->
    </footer>
</body>
</html>

